# Generated by Django 2.2.3 on 2019-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image1',
            field=models.CharField(default=1, max_length=1100),
            preserve_default=False,
        ),
    ]
