# Generated by Django 2.2.3 on 2019-07-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_mymodel_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image2',
            field=models.CharField(default=1, max_length=1120),
            preserve_default=False,
        ),
    ]
