# Generated by Django 2.2.3 on 2019-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_mymodel_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=240)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('product_img', models.CharField(max_length=1300)),
            ],
        ),
    ]
