# Generated by Django 2.2.3 on 2019-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
